const actionType = {
  HOTEL_SEARCH_SUCCESS: "HOTEL_SEARCH_SUCCESS",
  HOTEL_SEARCH_FAILURE: "HOTEL_SEARCH_FAILURE",
  HOTEL_FILTER_SUCCESS: "HOTEL_FILTER_SUCCESS",
  HOTEL_FILTER_FAILURE: "HOTEL_FILTER_FAILURE",
  ROOM_SEARCH_SUCCESS: "ROOM_SEARCH_SUCCESS",
  ROOM_SEARCH_FAILURE: "ROOM_SEARCH_FAILURE",
  ROOM_PRICE_SUCCESS: "ROOM_PRICE_SUCCESS",
  ROOM_PRICE_FAILURE: "ROOM_PRICE_FAILURE",
  ROOM_BOOKING_SUCCESS: "ROOM_BOOKING_SUCCESS",
  ROOM_BOOKING_FAILURE: "ROOM_BOOKING_FAILURE",
  ROOM_CANCEL_SUCCESS: "ROOM_CANCEL_SUCCESS",
  ROOM_CANCEL_FAILURE: "ROOM_BOOKING_FAILURE",
  ENABLE_LOADING_SEARCH: "ENABLE_LOADING_SEARCH",
  ENABLE_LOADING_SEARCH_FILTER: "ENABLE_LOADING_SEARCH_FILTER",
  DISABLE_LOADING_SEARCH_FILTER: "DISABLE_LOADING_SEARCH_FILTER",
  DISABLE_LOADING_SEARCH: "DISABLE_LOADING_SEARCH",
  ROOM_SEARCHSTATELESS_SUCCESS: "ROOM_SEARCHSTATELESS_SUCCESS",
  SEARCHBY_HOTEL_NAME: "SEARCHBY_HOTEL_NAME",
  ROOM_SEARCHSTATELESS_FAILURE: "ROOM_SEARCHSTATELESS_FAILURE",
  SEARCHBY_RATING:"SEARCHBY_RATING",
    PRICE_FILTER:"PRICE_FILTER"

};
export default actionType;