const actionType={
    PAYMENT_SUCCESS:"PAYMENT_SUCCESS",
    PAYMENT_FAILURE:"PAYMENT_FAILURE",
    PAYMENTWITHCARD_SUCCESS:"PAYMENTWITHCARD_SUCCESS",
    PAYMENTWITHCARD_FAILURE:"PAYMENTWITHCARD_FAILURE"
}
export default actionType