const actionType = {
CAR_FILTER_SUCCESS:"CAR_FILTER_SUCCESS",
CAR_FILTER_FAILURE:"CAR_FILTER_FAILURE",
CAR_SEARCH_SUCCESS:"CAR_SEARCH_SUCCESS",
CAR_SEARCH_FAILURE:"CAR_SEARCH_FAILURE",
CAR_GET_PRICE_SUCCESS:"CAR_GET_PRICE_SUCCESS",
CAR_GET_PRICE_FAILURE:"CAR_GET_PRICE_FAILURE",
CAR_BOOKING_SUCCESS:"CAR_BOOKING_SUCCESS",
CAR_BOOKING_FAILURE:"CAR_BOOKING_FAILURE"
}
export default actionType;