const actionType = {
  ADD_ITINERARY_SUCCESS: "ADD_ITINERARY_SUCCESS",
  ADD_ITINERARY_FAILURE: "ADD_ITINERARY_FAILURE",
  REMOVE_ITINERARY_SUCCESS: "REMOVE_ITINERARY_SUCCESS",
  REMOVE_ITINERARY_FAILURE: "REMOVE_ITINERARY_FAILURE"
};
export default actionType;
